receivers:
  filewatcher/regular:
    include: ["testdata/include"]
    exclude: ["testdata/exclude"]

  filewatcher/empty:
  filewatcher/problematic:
    include: ["testdata/-#{:,"]

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filewatcher]
      processors: []
      exporters: [debug]
