receivers:
  auditd:
    rules:
      - -w /etc/ssh/sshd_config -p warx -k sshd_config
      - -a always,exit -F arch=b64 -S exit -F auid>=1000 -F auid!=unset -F key=successful-login
      - "-a always,exit -S open,truncate -F dir=/etc -F success=0"
exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [auditd]
      processors: []
      exporters: [debug]
