// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/cloudoperators/opentelemetry-collector-contrib/exporter/opensearchexporter")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/cloudoperators/opentelemetry-collector-contrib/exporter/opensearchexporter")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                  metric.Meter
	mu                                     sync.Mutex
	registrations                          []metric.Registration
	OpensearchExporterOnErrorDocs          metric.Int64Counter
	OpensearchExporterOnErrorFlushFailures metric.Int64Counter
	OpensearchExporterPermanentErrors      metric.Int64Counter
	OpensearchExporterTransientErrors      metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.OpensearchExporterOnErrorDocs, err = builder.meter.Int64Counter(
		"otelcol_opensearch_exporter_on_error_docs",
		metric.WithDescription("Number of documents routed to the on-error index due to permanent indexing failures. [Alpha]"),
		metric.WithUnit("{document}"),
	)
	errs = errors.Join(errs, err)
	builder.OpensearchExporterOnErrorFlushFailures, err = builder.meter.Int64Counter(
		"otelcol_opensearch_exporter_on_error_flush_failures",
		metric.WithDescription("Number of failures when flushing documents to the on-error index. [Alpha]"),
		metric.WithUnit("{failure}"),
	)
	errs = errors.Join(errs, err)
	builder.OpensearchExporterPermanentErrors, err = builder.meter.Int64Counter(
		"otelcol_opensearch_exporter_permanent_errors",
		metric.WithDescription("Number of documents that encountered a permanent indexing error. [Alpha]"),
		metric.WithUnit("{document}"),
	)
	errs = errors.Join(errs, err)
	builder.OpensearchExporterTransientErrors, err = builder.meter.Int64Counter(
		"otelcol_opensearch_exporter_transient_errors",
		metric.WithDescription("Number of documents that encountered a transient (retriable) indexing error. [Alpha]"),
		metric.WithUnit("{document}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
